# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isComplete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='socialUrl',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, help_text='ISO Alpha-3 code', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialId',
            field=models.CharField(blank=True, help_text='FB social auth ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='degree',
            name='abbrev',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
