# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161219_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmetag',
            name='description',
            field=models.CharField(blank=True, help_text='Used for tooltip', max_length=200),
        ),
        migrations.AddField(
            model_name='cmetag',
            name='priority',
            field=models.IntegerField(default=0, help_text='Used for non-alphabetical sort.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.CmeTag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degrees',
            field=models.ManyToManyField(blank=True, to='users.Degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='users.PracticeSpecialty'),
        ),
    ]
