# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20161228_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmetag',
            options={'ordering': ['-priority', 'name'], 'verbose_name_plural': 'CME Tags'},
        ),
        migrations.AddField(
            model_name='profile',
            name='inviter',
            field=models.ForeignKey(blank=True, help_text='Set during profile creation to the user whose inviteId was provided upon first login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
