# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170124_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='billingCycle',
            field=models.PositiveIntegerField(default=1, help_text='Braintree current_billing_cycle'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billingEndDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Braintree billing_period_end_date - regardless of status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billingFirstDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Braintree first_bill_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billingStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Braintree billing_period_start_date - regardless of status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='display_status',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Active-Canceled', 'Active-Canceled'), ('Suspended', 'Suspended'), ('Expired', 'Expired')], help_text='Status for UI display', max_length=40),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Past Due', 'Past Due'), ('Pending', 'Pending')], help_text='Braintree-defined status', max_length=10),
        ),
    ]
