# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170131_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='billingEndDate',
            field=models.DateTimeField(blank=True, help_text='Braintree billing_period_end_date - regardless of status', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='billingFirstDate',
            field=models.DateTimeField(blank=True, help_text='Braintree first_bill_date', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='billingStartDate',
            field=models.DateTimeField(blank=True, help_text='Braintree billing_period_start_date - regardless of status', null=True),
        ),
    ]
