# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20170131_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=users.models.entry_document_path)),
                ('name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('md5sum', models.CharField(blank=True, help_text='md5sum of the document file', max_length=32)),
                ('content_type', models.CharField(blank=True, help_text='file content_type', max_length=100)),
                ('image_h', models.PositiveIntegerField(blank=True, help_text='image height', null=True)),
                ('image_w', models.PositiveIntegerField(blank=True, help_text='image width', null=True)),
                ('is_thumb', models.BooleanField(default=False, help_text='True if the file is an image thumbnail')),
                ('uploadId', models.CharField(max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='md5sum',
        ),
        migrations.AddField(
            model_name='entry',
            name='uploadId',
            field=models.CharField(blank=True, help_text='To connect an entry with uploaded Documents', max_length=36),
        ),
        migrations.AddField(
            model_name='entry',
            name='documents',
            field=models.ManyToManyField(related_name='entries', to='users.Document'),
        ),
    ]
