# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170208_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.URLField(help_text='e.g. https://www.wikipedia.org/', max_length=500)),
                ('domain_title', models.CharField(blank=True, help_text='e.g. Wikipedia Anatomy Pages', max_length=300)),
                ('is_valid_domurl', models.BooleanField(default=True)),
                ('example_url', models.URLField(help_text='A URL within the given domain', max_length=1000)),
                ('example_title', models.CharField(blank=True, help_text='Label for the example URL', max_length=300)),
                ('is_valid_expurl', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('needs_ad_block', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification', serialize=False, to='users.Entry')),
                ('expireDate', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True, help_text='Link to website of sponsor', max_length=1000)),
                ('logo_url', models.URLField(help_text='Link to logo of sponsor', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exbrowsercme',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='exbrowsercme',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='entry',
        ),
        migrations.AddField(
            model_name='practicespecialty',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, help_text='Eligible cmeTags for this specialty', related_name='specialties', to='users.CmeTag'),
        ),
        migrations.DeleteModel(
            name='ExBrowserCme',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='users.PracticeSpecialty'),
        ),
        migrations.AddField(
            model_name='entry',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Sponsor'),
        ),
    ]
