# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170221_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': (('view_feed', 'Can view Feed'), ('post_srcme', 'Can post Self-reported Cme entry'), ('post_brcme', 'Can redeem BrowserCmeOffer'), ('view_dashboard', 'Can view Dashboard'), ('print_brcme_cert', 'Can print/share BrowserCme certificate'), ('print_audit_report', 'Can print/share audit report')), 'verbose_name_plural': 'Entries'},
        ),
    ]
