# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170221_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browsercmeoffer',
            options={'permissions': (('view_offer', 'Can view BrowserCmeOffer'),), 'verbose_name_plural': 'BrowserCME Offers'},
        ),
    ]
