# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170302_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligiblesite',
            name='domain_title',
            field=models.CharField(help_text='e.g. Wikipedia Anatomy Pages', max_length=300),
        ),
    ]
