# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20170302_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceId', models.CharField(help_text='alphanum key of the certitficate', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Name on certificate', max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('document', models.FileField(upload_to=users.models.certificate_document_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
