# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170311_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_certificate',
            field=models.BooleanField(default=False, help_text='True if file is a certificate (if so, will be shared in audit report)'),
        ),
    ]
