# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_allowedhost_allowedurl_auditreport_requestedurl_whitelistrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditreport',
            name='certificate',
            field=models.ForeignKey(help_text='BrowserCme Certificate generated for the same date range', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Certificate'),
        ),
    ]
