# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170330_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='referenceId',
            field=models.CharField(blank=True, default=None, help_text='alphanum unique key generated from the document id', max_length=255, null=True, unique=True),
        ),
    ]
