# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 06:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_document_referenceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditreport',
            name='document',
        ),
        migrations.AddField(
            model_name='auditreport',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'data': ''}),
            preserve_default=False,
        ),
    ]
