# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170331_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
