# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170417_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pictureUrl',
            field=models.URLField(blank=True, help_text='Auth0 avatar URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socialId',
            field=models.CharField(blank=True, help_text='Auth0 ID', max_length=64),
        ),
    ]
