# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_pinnedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedmessage',
            name='launch_url',
            field=models.URLField(default='http://www.example.com', help_text='A URL within the given domain', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='npiFirstName',
            field=models.CharField(blank=True, help_text='First name from NPI Registry', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='npiLastName',
            field=models.CharField(blank=True, help_text='Last name from NPI Registry', max_length=30),
        ),
    ]
