# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20170508_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedmessage',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Sponsor'),
        ),
    ]
