# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_pinnedmessage_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessedTour',
            field=models.BooleanField(default=False, help_text='User has commenced the online product tour'),
        ),
        migrations.AlterField(
            model_name='pinnedmessage',
            name='launch_url',
            field=models.URLField(help_text='A URL for the Launch button', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, help_text='User has verified their email via Auth0'),
        ),
    ]
