# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170524_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, default=1, help_text='discounted price in USD', max_digits=6),
            preserve_default=False,
        ),
    ]
