# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_subscriptionplan_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=36, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text=' in USD', max_digits=6)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.UserSubscription')),
            ],
        ),
    ]
