# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_subscriptiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='card_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='receipt_sent',
            field=models.BooleanField(default=False, help_text='set to True on sending of receipt via email'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='remindRenewSent',
            field=models.BooleanField(default=False, help_text='set to True upon sending of auto-renewal reminder via email'),
        ),
    ]
