# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20170609_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='proc_auth_code',
            field=models.CharField(blank=True, help_text='processor_authorization_code', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='proc_response_code',
            field=models.CharField(blank=True, help_text='processor_response_code', max_length=4),
        ),
    ]
