# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20170612_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ama_pra_catg',
            field=models.CharField(blank=True, help_text='AMA PRA Category', max_length=2),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='certificate',
            field=models.ForeignKey(help_text='BrowserCme Certificate generated for the same date range', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditreports', to='users.Certificate'),
        ),
    ]
