# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20170615_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmetag',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
