# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_practicespecialty_is_abms_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='failure_alert_sent',
            field=models.BooleanField(default=False, help_text='set to True on sending of payment failure alert via email'),
        ),
    ]
