# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20170629_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercmeoffer',
            name='eligible_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.EligibleSite'),
        ),
    ]
