# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_browsercmeoffer_eligible_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercmeoffer',
            name='eligible_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.EligibleSite'),
            preserve_default=False,
        ),
    ]
