# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20170706_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercmeoffer',
            name='suggestedDescr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practicespecialty',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this entry is a sub-specialty, then specify its GeneralCert parent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PracticeSpecialty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cmeDuedate',
            field=models.DateTimeField(blank=True, help_text='Due date for CME requirements fulfillment', null=True),
        ),
    ]
