# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20170710_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblesite',
            name='page_title_suffix',
            field=models.CharField(blank=True, default='', help_text='Common suffix for page titles', max_length=60),
        ),
    ]
