# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20170717_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='npiType',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Organization')], default=1, help_text='Type 1 (Individual). Type 2 (Organization).'),
        ),
    ]
