# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_profile_npitype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCmeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrowserCmeOffer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmeTag')),
            ],
        ),
        migrations.AddField(
            model_name='browsercmeoffer',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, help_text='Suggested tags (intersected with user cmeTags by UI)', related_name='brcmeoffers', through='users.OfferCmeTag', to='users.CmeTag'),
        ),
    ]
