# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20170801_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblesite',
            name='all_specialties',
            field=models.BooleanField(default=False),
        ),
    ]
