# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_eligiblesite_all_specialties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offercmetag',
            unique_together=set([('offer', 'tag')]),
        ),
    ]
