# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20170802_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='degree',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
