# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20170815_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nbcrnaId',
            field=models.CharField(blank=True, help_text='NBCRNA ID for Nurse Anesthetists', max_length=20),
        ),
    ]
