# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_profile_nbcrnaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nbcrnaId',
            field=models.CharField(blank=True, default='', help_text='NBCRNA ID for Nurse Anesthetists', max_length=20),
        ),
    ]
