# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20170818_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statelicense',
            old_name='expireDate',
            new_name='expiryDate',
        ),
    ]
