# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_discount_invitationdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['discountType', '-created']},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='activeInvitee',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='activeInviter',
        ),
        migrations.AddField(
            model_name='discount',
            name='activeForType',
            field=models.BooleanField(default=False, help_text='True if this is the active discount for its type'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discountType',
            field=models.CharField(default='invitee', help_text='Discount Type: lowercased', max_length=40),
            preserve_default=False,
        ),
    ]
