# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20170828_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationdiscount',
            name='creditEarned',
            field=models.BooleanField(default=False, help_text='True if inviter earns actual credit for this invitee as opposed to just karma.'),
        ),
        migrations.AddField(
            model_name='invitationdiscount',
            name='inviterBillingCycle',
            field=models.PositiveIntegerField(default=1, help_text='Billing cycle of inviter at the time their subscription was updated.'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='nextBillingAmount',
            field=models.DecimalField(decimal_places=2, default=0, help_text=' BT next_billing_period_amount in USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='billingCycle',
            field=models.PositiveIntegerField(default=1, help_text='BT current_billing_cycle'),
        ),
    ]
