# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20170829_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='trans_type',
            field=models.CharField(default='sale', help_text='sale or credit. If credit, then amount was refunded', max_length=10),
        ),
    ]
