# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0063_hostpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('starts_with', models.BooleanField(default=False, help_text='True if any sub URL under it should also be rejected')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_rejectedurl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('affiliateId', models.CharField(help_text='Affiliate ID', max_length=6, unique=True)),
                ('paymentEmail', models.EmailField(help_text='Valid email address to be used for Payouts.', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('bonus', models.DecimalField(decimal_places=2, help_text='payout amount per converted user in USD', max_digits=5)),
                ('personalText', models.TextField(blank=True, default='', help_text='Custom personal text for display')),
                ('photoUrl', models.URLField(help_text='Link to affiliate photo', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('convertee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('payoutItemId', models.CharField(blank=True, help_text='PayPal-generated item identifier. Exists even if there is no transactionId.', max_length=36)),
                ('transactionId', models.CharField(blank=True, help_text='PayPal-generated id for the transaction.', max_length=36)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid to affiliate in USD.', max_digits=5)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction fee in USD', max_digits=4, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DENIED', 'DENIED'), ('NEW', 'NEW'), ('BLOCKED', 'BLOCKED'), ('FAILED', 'FAILED'), ('ONHOLD', 'ONHOLD'), ('REFUNDED', 'REFUNDED'), ('RETURNED', 'RETURNED'), ('UNCLAIMED', 'UNCLAIMED')], help_text='PayPal-defined item transaction status', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='BatchPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_batch_id', models.CharField(max_length=36, unique=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('payout_batch_id', models.CharField(blank=True, help_text='PayPal-generated ID for a batch payout.', max_length=36)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('DENIED', 'DENIED'), ('NEW', 'NEW'), ('CANCELED', 'CANCELED')], help_text='PayPal-defined status of batch payout request', max_length=20)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Batch amount paid', max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, help_text='Amount currency', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_affiliate',
            field=models.BooleanField(default=False, help_text='True if user is an approved affiliate'),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='batchpayout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afflpayouts', to='users.BatchPayout'),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='converteeDiscount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converteediscounts', to='users.Discount'),
        ),
    ]
