# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20171016_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='photoUrl',
            field=models.URLField(blank=True, help_text='Link to affiliate photo', max_length=1000),
        ),
    ]
