# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20171016_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cmeTags',
        ),
        migrations.AddField(
            model_name='profile',
            name='oldcmeTags',
            field=models.ManyToManyField(blank=True, to='users.CmeTag'),
        ),
    ]
