# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20171016_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCmetag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmeTag')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='users.ProfileCmetag', to='users.CmeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='profilecmetag',
            unique_together=set([('profile', 'tag')]),
        ),
    ]
