# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20171016_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='og_description',
            field=models.TextField(blank=True, default='', help_text='Value for og:description metatag'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='og_image',
            field=models.URLField(blank=True, help_text='URL for og:image metatag', max_length=1000),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='og_title',
            field=models.TextField(blank=True, default='Orbit', help_text='Value for og:title metatag'),
        ),
    ]
