# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20171017_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='jobDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batchpayout',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='Amount currency', max_length=4),
        ),
    ]
