# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20171020_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepayout',
            name='payoutItemId',
            field=models.CharField(blank=True, default='', help_text='PayPal-generated item identifier. Exists even if there is no transactionId.', max_length=36),
        ),
        migrations.AlterField(
            model_name='affiliatepayout',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('DENIED', 'DENIED'), ('NEW', 'NEW'), ('BLOCKED', 'BLOCKED'), ('FAILED', 'FAILED'), ('ONHOLD', 'ONHOLD'), ('REFUNDED', 'REFUNDED'), ('RETURNED', 'RETURNED'), ('UNCLAIMED', 'UNCLAIMED'), ('unset', 'unset')], default='unset', help_text='PayPal-defined item transaction status', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliatepayout',
            name='transactionId',
            field=models.CharField(blank=True, default='', help_text='PayPal-generated id for the transaction.', max_length=36),
        ),
    ]
