# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20171023_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatepayout',
            name='fee',
        ),
        migrations.AlterField(
            model_name='batchpayout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('DENIED', 'DENIED'), ('NEW', 'NEW'), ('CANCELED', 'CANCELED'), ('unset', 'unset')], default='unset', help_text='PayPal-defined status of batch payout request', max_length=20),
        ),
    ]
