# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20171025_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(max_length=40)),
                ('expireDate', models.DateTimeField(verbose_name='Cutoff for user signup date [UTC]')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(help_text='Discount to be applied to first billingCycle', on_delete=django.db.models.deletion.CASCADE, related_name='signupdiscounts', to='users.Discount')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='signupdiscount',
            unique_together=set([('email_domain', 'discount', 'expireDate')]),
        ),
    ]
