# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20171025_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='discountLabel',
            field=models.CharField(blank=True, default='', help_text='identifying label used in discount display', max_length=60),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='affiliateId',
            field=models.CharField(help_text='Affiliate ID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='photoUrl',
            field=models.URLField(blank=True, help_text='Link to photo', max_length=1000),
        ),
    ]
