# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20171031_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Fractional multipler on fully discounted priced paid by convertee', max_digits=3),
        ),
    ]
