# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliateId', models.CharField(help_text='Affiliate ID', max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('personalText', models.TextField(blank=True, default='', help_text='Custom personal text for display')),
                ('photoUrl', models.URLField(blank=True, help_text='Link to photo', max_length=500)),
                ('jobDescription', models.TextField(blank=True)),
                ('og_title', models.TextField(blank=True, default='Orbit', help_text='Value for og:title metatag')),
                ('og_description', models.TextField(blank=True, default='', help_text='Value for og:description metatag')),
                ('og_image', models.URLField(blank=True, help_text='URL for og:image metatag', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='active',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='affiliateId',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='jobDescription',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='personalText',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='photoUrl',
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliateId',
            field=models.CharField(blank=True, help_text='If conversion, specify Affiliate ID', max_length=20),
        ),
        migrations.AddField(
            model_name='affiliatedetail',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affdetails', to='users.Affiliate'),
        ),
    ]
