# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20171102_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdiscount',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signupdiscounts', to='users.Organization'),
            preserve_default=False,
        ),
    ]
