# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_signupdiscount_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatedetail',
            name='redirect_page',
            field=models.CharField(blank=True, default='', help_text='Name of HTML page for redirect - e.g. orbitPA.html', max_length=80),
        ),
    ]
