# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_affiliatedetail_redirect_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='users.CmeTag'),
        ),
    ]
