# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_certificate_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='oldcmeTags',
        ),
        migrations.AlterField(
            model_name='cmetag',
            name='description',
            field=models.CharField(blank=True, help_text='Long-form name', max_length=200),
        ),
    ]
