# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20171113_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cmeDuedate',
            new_name='cmeEndDate',
        ),
    ]
