# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20171113_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cmeStartDate',
            field=models.DateTimeField(blank=True, help_text='Start date for CME requirements calculation', null=True),
        ),
    ]
