# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_profile_cmestartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='rncertValid',
            field=models.BooleanField(default=False, help_text='True if RN/NP certificate is valid in this state'),
        ),
    ]
