# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_certificate_state_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmetag',
            name='description',
            field=models.CharField(help_text='Long-form name', max_length=200, unique=True),
        ),
    ]
