# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_auto_20171211_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, default=1, help_text='CME credits to be awarded upon completion (default = 1)', max_digits=4)),
                ('startDate', models.DateTimeField()),
                ('expireDate', models.DateField(help_text='Expiration date for display')),
                ('endDate', models.DateTimeField(help_text='Expiration timestamp used by server')),
                ('launch_url', models.URLField(help_text='Form URL', max_length=1000)),
                ('entry_url', models.URLField(help_text='URL for the feed entry.', max_length=1000)),
                ('entry_title', models.URLField(help_text='Title for the feed entry.', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Sponsor')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
