# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='entry_title',
            field=models.URLField(help_text='Article title will be copied to the feed entries.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='entry_url',
            field=models.URLField(help_text='Article URL will be copied to the feed entries.', max_length=1000),
        ),
    ]
