# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_auto_20171212_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCme',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storycme', serialize=False, to='users.Entry')),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url', models.URLField(max_length=500)),
                ('title', models.TextField()),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='storycme', to='users.Story')),
            ],
        ),
    ]
