# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_auto_20171212_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='display_status',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Active-Canceled', 'Active-Canceled'), ('Suspended', 'Suspended'), ('Expired', 'Expired'), ('Trial-Canceled', 'Trial-Canceled'), ('Active-Downgrade', 'Active-Downgrade')], help_text='Status for UI display', max_length=40),
        ),
    ]
