# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0099_auto_20180116_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthImpersonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireDate', models.DateTimeField(default=users.models.default_expire)),
                ('valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('impersonatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonatees', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
