# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_authimpersonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='downgrade_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downgrade_plans', to='users.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='maxCmeMonth',
            field=models.IntegerField(default=0, help_text='maximum allowed CME per month'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='maxCmeWeek',
            field=models.IntegerField(default=0, help_text='maximum allowed CME per week'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='maxCmeYear',
            field=models.IntegerField(default=0, help_text='maximum allowed CME per year'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='upgrade_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_plans', to='users.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='users.SubscriptionPlanKey'),
        ),
    ]
