# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_auto_20180214_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplankey',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_keys', to='users.Degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplankey',
            name='specialty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_keys', to='users.PracticeSpecialty'),
        ),
    ]
