# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20180214_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jobTitle',
        ),
        migrations.AddField(
            model_name='profile',
            name='planId',
            field=models.CharField(blank=True, help_text='planId selected at signup', max_length=36),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='downgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downgrade_plans', to='users.SubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Display name (e.g. NP Standard)', max_length=80),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='planId',
            field=models.CharField(help_text='Unique. No whitespace. Must be in sync with the actual plan in Braintree', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='users.SubscriptionPlanKey'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trialDays',
            field=models.IntegerField(default=7, help_text='Trial period in days'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='upgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_plans', to='users.SubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplankey',
            name='name',
            field=models.CharField(help_text='Must be unique. Must match the landing_key in the pricing page URL', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplankey',
            name='specialty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_keys', to='users.PracticeSpecialty'),
        ),
    ]
