# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_auto_20180216_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitCmeOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityDate', models.DateTimeField()),
                ('suggestedDescr', models.TextField(blank=True, default='')),
                ('expireDate', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('credits', models.DecimalField(decimal_places=2, help_text='CME credits to be awarded upon redemption', max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_orbitcmeoffer',
                'managed': False,
                'verbose_name_plural': 'OrbitCME Offers',
            },
        ),
    ]
