# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_orbitcmeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercme',
            name='offerId',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
