# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_browsercme_offerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercme',
            name='offer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brcme', to='users.BrowserCmeOffer'),
        ),
    ]
