# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_auto_20180223_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblesite',
            name='verify_journal',
            field=models.BooleanField(default=False, help_text='If True, need to verify article belongs to an allowed journal before making offer.'),
        ),
    ]
