# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_eligiblesite_verify_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsercmeoffer',
            name='cmeTags',
        ),
        migrations.RemoveField(
            model_name='browsercmeoffer',
            name='eligible_site',
        ),
        migrations.RemoveField(
            model_name='browsercmeoffer',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='browsercmeoffer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='offercmetag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='offercmetag',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offercmetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='browsercme',
            name='offer',
        ),
        migrations.DeleteModel(
            name='BrowserCmeOffer',
        ),
        migrations.DeleteModel(
            name='OfferCmeTag',
        ),
    ]
