# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_auto_20180313_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': (('view_feed', 'Can view Feed'), ('view_dashboard', 'Can view Dashboard'), ('post_brcme', 'Can redeem BrowserCmeOffer'), ('delete_brcme', 'Can delete BrowserCme entry'), ('post_srcme', 'Can post Self-reported Cme entry'), ('print_audit_report', 'Can print/share audit report'), ('print_brcme_cert', 'Can print/share BrowserCme certificate')), 'verbose_name_plural': 'Entries'},
        ),
    ]
