# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_auto_20180313_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='maxCmeWeek',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeMonth',
            field=models.PositiveIntegerField(default=0, help_text='maximum allowed CME per month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeYear',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed CME per year. 0 for unlimited.'),
        ),
    ]
