# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_auto_20180313_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': (('view_feed', 'Can view Feed'), ('view_dashboard', 'Can view Dashboard'), ('post_brcme', 'Can redeem BrowserCmeOffer'), ('delete_brcme', 'Can delete BrowserCme entry'), ('edit_brcme', 'Can edit BrowserCme entry'), ('post_srcme', 'Can post Self-reported Cme entry'), ('print_audit_report', 'Can print/share audit report'), ('print_brcme_cert', 'Can print/share BrowserCme certificate')), 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeMonth',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed CME per month. 0 for unlimited rate.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeYear',
            field=models.PositiveIntegerField(default=0, help_text='Target CME per year. For limited plans, this is also a maximum allowed per year.'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='next_plan',
            field=models.ForeignKey(blank=True, default=None, help_text='Used to store plan for pending downgrade', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan'),
        ),
    ]
