# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_auto_20180320_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercme',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brcmes', to='users.UserFeedback'),
        ),
        migrations.AddField(
            model_name='browsercme',
            name='planText',
            field=models.CharField(blank=True, default='', help_text='Optional explanation of changes to clinical plan', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeYear',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed CME per year. 0 for unlimited total.'),
        ),
    ]
