# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_auto_20180406_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsercme',
            name='feedback',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='entry',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='users.Entry'),
        ),
    ]
