# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_auto_20180406_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligiblesite',
            name='is_valid_expurl',
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='doi_prefixes',
            field=models.CharField(blank=True, default='', help_text='Comma separated list of common doi prefixes of articles of this site', max_length=80),
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='electronic_issn',
            field=models.CharField(blank=True, default='', help_text='Electronic ISSN', max_length=9),
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='issn',
            field=models.CharField(blank=True, default='', help_text='ISSN', max_length=9),
        ),
    ]
