# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_auto_20180413_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEmailPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_year_price', models.DecimalField(decimal_places=2, help_text='First year promotional price', max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
