# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_signupemailpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupemailpromo',
            name='display_label',
            field=models.CharField(blank=True, default='', help_text='Display label shown to the user in the discount screen', max_length=60),
        ),
    ]
