# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_auto_20180619_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercme',
            name='competence',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unsure')], default=1, help_text='Change in competence - conceptual understanding'),
        ),
        migrations.AddField(
            model_name='browsercme',
            name='performance',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unsure')], default=1, help_text='Change in performance - transfer of knowledge to practice'),
        ),
        migrations.AddField(
            model_name='practicespecialty',
            name='planText',
            field=models.CharField(blank=True, default='', help_text='Default response for changes to clinical plan', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionplankey',
            name='use_free_plan',
            field=models.BooleanField(default=False, help_text='If true: expects a Free Standard Plan assigned to it, to be used in place of the BT Standard Plan for signup'),
        ),
    ]
