# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_auto_20180718_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercme',
            name='commercialBias',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unsure')], default=0, help_text='Commercial bias in content'),
        ),
        migrations.AddField(
            model_name='browsercme',
            name='commercialBiasText',
            field=models.CharField(blank=True, default='', help_text='Explanation of commercial bias in content', max_length=500),
        ),
        migrations.AlterField(
            model_name='browsercme',
            name='planText',
            field=models.CharField(blank=True, default='', help_text='Explanation of changes to clinical plan', max_length=500),
        ),
        migrations.AlterField(
            model_name='signupdiscount',
            name='expireDate',
            field=models.DateTimeField(help_text='Cutoff for user signup date [UTC]'),
        ),
    ]
