# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_auto_20180721_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Practice Sub Specialties',
            },
        ),
        migrations.RemoveField(
            model_name='practicespecialty',
            name='parent',
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecialties', to='users.PracticeSpecialty'),
        ),
        migrations.AlterUniqueTogether(
            name='subspecialty',
            unique_together=set([('specialty', 'name')]),
        ),
    ]
