# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_auto_20180723_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('hasResidencyProgram', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='users.State')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together=set([('state', 'city', 'name')]),
        ),
    ]
