# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_auto_20180724_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Used for display', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliationText',
            field=models.CharField(blank=True, default='', help_text='User specified affiliation', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='users.Hospital'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interestText',
            field=models.CharField(blank=True, default='', help_text='User specified interests', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='users.Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency',
            field=models.ForeignKey(blank=True, help_text='Residency Program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencies', to='users.Hospital'),
        ),
        migrations.AddField(
            model_name='profile',
            name='residencyEndDate',
            field=models.DateField(blank=True, help_text='Date of completion of residency program', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='states',
            field=models.ManyToManyField(blank=True, to='users.State'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subspecialties',
            field=models.ManyToManyField(blank=True, to='users.SubSpecialty'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
