# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_auto_20180727_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedmessage',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='pinnedmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PinnedMessage',
        ),
    ]
