# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0125_auto_20180802_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statelicense',
            old_name='expiryDate',
            new_name='expireDate',
        ),
        migrations.AlterField(
            model_name='invitationdiscount',
            name='inviterDiscount',
            field=models.ForeignKey(blank=True, help_text='Set when inviter subscription has been updated with the discount', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviterdiscounts', to='users.Discount'),
        ),
        migrations.AlterUniqueTogether(
            name='statelicense',
            unique_together=set([('user', 'state', 'license_type', 'license_no', 'expireDate')]),
        ),
    ]
