# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0126_auto_20180802_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statelicense',
            old_name='license_type',
            new_name='licenseType',
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='statelicense',
            unique_together=set([('user', 'state', 'licenseType', 'expireDate')]),
        ),
    ]
