# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_auto_20180807_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statelicense',
            old_name='license_no',
            new_name='licenseNumber',
        ),
    ]
