# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_auto_20180808_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecAllowedUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trackers_recallowedurl',
                'managed': False,
            },
        ),
    ]
