# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_auto_20180815_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='socialId',
            field=models.CharField(blank=True, db_index=True, help_text='Auth0 ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Internal Plan name (alphanumeric only). If plan_type is Braintree, it must match value in Braintree. Will be used to set planId.', max_length=80),
        ),
    ]
