# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0131_auto_20180816_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=users.models.base.orgfile_document_path)),
                ('name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('content_type', models.CharField(blank=True, help_text='file content_type', max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgfiles', to='users.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enterprise File Uploads',
            },
        ),
        migrations.AddField(
            model_name='orgmember',
            name='orgfiles',
            field=models.ManyToManyField(related_name='orgmembers', to='users.OrgFile'),
        ),
    ]
