# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_orgfile_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='users.SubscriptionPlanType'),
            preserve_default=False,
        ),
    ]
