# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_auto_20180822_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, help_text='cmeTags to be added to profile for users who select this state', related_name='states', to='users.CmeTag'),
        ),
    ]
