# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_state_cmetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='compliance',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Cached compliance level aggregated over user goals'),
        ),
    ]
