# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_auto_20180830_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitCmeOfferAgg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('offers', models.PositiveIntegerField(default=0, help_text='Number of offers generated for this day (counted from 00:00:00 UTC - 23:59:59 UTC)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_orbitcmeofferagg',
                'managed': False,
                'verbose_name_plural': 'OrbitCME Offer Stats',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='creditStartDate',
            field=models.DateTimeField(blank=True, help_text='Start date of total credits calculation', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='credits',
            field=models.FloatField(default=0, help_text='Computed total credits earned by this org since creditStartDate until today.'),
        ),
    ]
