# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 06:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_auto_20180904_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='creditEndDate',
            field=models.DateTimeField(blank=True, help_text='End date of total credits calculation', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='providerStat',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
    ]
