# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0139_auto_20180905_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deaStates',
            field=models.ManyToManyField(blank=True, related_name='dea_profiles', to='users.State'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='orgfiles',
            field=models.ManyToManyField(blank=True, related_name='orgmembers', to='users.OrgFile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.Hospital'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.State'),
        ),
    ]
