# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_auto_20180927_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasDEA',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=None, help_text='Does user have DEA registration. Value is 0, 1 or null for unset', null=True),
        ),
    ]
