# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_profile_hasdea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='display_status',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Active', 'Active'), ('Active-Canceled', 'Active-Canceled'), ('Suspended', 'Suspended'), ('Expired', 'Expired'), ('Trial-Canceled', 'Trial-Canceled'), ('Active-Downgrade-Scheduled', 'Active-Downgrade-Scheduled'), ('Enterprise-Canceled', 'Enterprise-Canceled')], help_text='Status for UI display', max_length=40),
        ),
    ]
