# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0142_auto_20181010_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='joinCode',
            field=models.CharField(default='', help_text='Join Code for invitation URL', max_length=20),
        ),
    ]
