# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_organization_joincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsercme',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='browsercme',
            name='offerId',
            field=models.PositiveIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
