# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_auto_20181015_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used in UI form. Must be unique', max_length=40, unique=True)),
                ('category', models.CharField(help_text='Value only. e.g. 1-A', max_length=4)),
                ('auditname', models.CharField(help_text='Name used in audit report', max_length=60)),
                ('needs_tm', models.BooleanField(default=False, help_text='True if UI should display Trademark symbol for it')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('degrees', models.ManyToManyField(blank=True, help_text='Applicable to the specified Degrees. Blank=All', related_name='creditTypes', to='users.Degree')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='entries', to='users.Document'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='users.EntryType'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='users.Sponsor'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='users.CmeTag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='creditType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='users.CreditType'),
        ),
    ]
