# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0145_auto_20181016_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='credittype',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, help_text='Sort order for choices in form.'),
            preserve_default=False,
        ),
    ]
