# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0146_auto_20181016_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='pending',
            field=models.BooleanField(default=False, help_text='Set to True when invitation is sent to existing user to join team.'),
        ),
    ]
