# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0147_orgmember_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmeBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('credits', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text=' in USD', max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CmeBoostPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=36, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text=' in USD', max_digits=6)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('proc_auth_code', models.CharField(blank=True, help_text='processor_authorization_code', max_length=10)),
                ('proc_response_code', models.CharField(blank=True, help_text='processor_response_code', max_length=4)),
                ('receipt_sent', models.BooleanField(default=False, help_text='set to True on send receipt email')),
                ('failure_alert_sent', models.BooleanField(default=False, help_text='set to True on send payment failure alert via email')),
                ('trans_type', models.CharField(default='sale', help_text='sale or credit', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('boost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boosts', to='users.CmeBoost')),
            ],
        ),
        migrations.CreateModel(
            name='UserCmeCredit',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boost_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='maxCmeYear',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed CME per plan period (defined via billingCycleMonths - can be one or multiple years). 0 for unlimited total.'),
        ),
        migrations.AddField(
            model_name='cmeboostpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cme_boosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
