# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0148_auto_20181112_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='certificates',
            field=models.ManyToManyField(blank=True, help_text='Specialty Certificates generated for the same date range', related_name='auditreports', to='users.Certificate'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='certificate',
            field=models.ForeignKey(help_text='Certificate generated for the same date range', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genauditreports', to='users.Certificate'),
        ),
        migrations.AlterField(
            model_name='subscriptionplankey',
            name='use_free_plan',
            field=models.BooleanField(default=False, help_text='If true: expects a Free Plan assigned to it, to be used in place of the BT Plan for signup'),
        ),
    ]
