# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0149_auto_20181119_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='ama_pra_catg',
        ),
        migrations.AddField(
            model_name='cmetag',
            name='notes',
            field=models.TextField(default='', help_text='Long-form text. Used for self-reported cme tags'),
        ),
        migrations.AddField(
            model_name='cmetag',
            name='srcme_only',
            field=models.BooleanField(default=False, help_text='True if tag is only valid for self-reported cme'),
        ),
        migrations.AlterField(
            model_name='cmetag',
            name='description',
            field=models.CharField(help_text='Long-form name. Must be unique. Used on certificates.', max_length=200, unique=True),
        ),
    ]
