# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0151_auto_20190107_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittype',
            name='category',
        ),
        migrations.AddField(
            model_name='credittype',
            name='abbrev',
            field=models.CharField(default='1', help_text='Abbreviation used in Track View e.g. AMA-1 or AOA-1A', max_length=8),
            preserve_default=False,
        ),
    ]
