# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0152_auto_20190115_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Uppercase first and last name for search', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enterprise Practice Divisions',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(help_text='Org short code (ASCII only - used to create joinCode for command-line arguments)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='orggroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orggroups', to='users.Organization'),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgmembers', to='users.OrgGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='orggroup',
            unique_together=set([('organization', 'name')]),
        ),
    ]
