# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0154_auto_20190116_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDeatag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dea_in_state', models.BooleanField(default=True, help_text='True if user needs DEA license in this particular state. False if any state')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.State')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmeTag')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='state',
            name='deaTags',
            field=models.ManyToManyField(blank=True, help_text='cmeTags to be added to profile for users with DEA licenses', related_name='deastates', through='users.StateDeatag', to='users.CmeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='statedeatag',
            unique_together=set([('state', 'tag')]),
        ),
    ]
