# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 10:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0156_state_dotags'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
    ]
