# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0157_orgmember_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='residency',
            field=models.ForeignKey(blank=True, help_text='Residency Program from Hospital [old]', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hresidencies', to='users.Hospital'),
        ),
        migrations.AddField(
            model_name='profile',
            name='residency_program',
            field=models.ForeignKey(blank=True, help_text='Residency Program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencies', to='users.ResidencyProgram'),
        ),
    ]
