# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0159_auto_20190225_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='inviteDate',
            field=models.DateTimeField(blank=True, help_text='date the member was last invited. This is updated each time the invite email is re-sent to the user.', null=True),
        ),
    ]
