# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0160_orgmember_invitedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='snapshotDate',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the snapshot generation', null=True),
        ),
    ]
