# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0162_auto_20190312_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='statelicense',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to false when license is inactivated'),
        ),
        migrations.AddField(
            model_name='statelicense',
            name='removeDate',
            field=models.DateTimeField(blank=True, help_text='Set when license is in-activated', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statelicense',
            unique_together=set([('user', 'state', 'licenseType', 'expireDate', 'is_active')]),
        ),
    ]
