# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 05:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0163_auto_20190404_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('cme_gap_expired', models.IntegerField(help_text='Sum of user cme gaps for expired goals. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('cme_gap_expiring', models.IntegerField(help_text='Sum of user cme gaps for expiring goals. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('licenses_expired', models.IntegerField(help_text='Number of expired user licenses. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('licenses_expiring', models.IntegerField(help_text='Number of expiring user licenses. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('users_invited', models.IntegerField(help_text='Number of invited users. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('users_active', models.IntegerField(help_text='Number of active users - accepted invitation. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('users_inactive', models.IntegerField(help_text='Number of removed users. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaggs', to='users.Organization')),
            ],
            options={
                'verbose_name_plural': 'Enterprise Aggregate Stats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orgagg',
            unique_together=set([('organization', 'day')]),
        ),
    ]
