# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 06:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0164_auto_20190423_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgagg',
            name='cme_gap_expired',
            field=models.IntegerField(default=0, help_text='Sum of user cme gaps for expired goals. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='cme_gap_expiring',
            field=models.IntegerField(default=0, help_text='Sum of user cme gaps for expiring goals. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='licenses_expired',
            field=models.IntegerField(default=0, help_text='Number of expired user licenses. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='licenses_expiring',
            field=models.IntegerField(default=0, help_text='Number of expiring user licenses. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='users_active',
            field=models.IntegerField(default=0, help_text='Number of active users - accepted invitation. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='users_inactive',
            field=models.IntegerField(default=0, help_text='Number of removed users. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orgagg',
            name='users_invited',
            field=models.IntegerField(default=0, help_text='Number of invited users. Calculated on a specific day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
