# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0165_auto_20190423_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fluoroscopyStates',
            field=models.ManyToManyField(blank=True, related_name='fluoroscopy_profiles', to='users.State'),
        ),
    ]
