# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0166_profile_fluoroscopystates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Abstract', max_length=40)),
                ('is_allowed', models.BooleanField(default=False, help_text='Check box if this ArticleType is allowed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_allowed', 'name'),
                'db_table': 'trackers_articletype',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='statelicense',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, help_text='User who created or last modified this row', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modstatelicenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
