# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0167_auto_20190511_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupemailpromo',
            name='first_year_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First year promotional discount (price and discount should not be specified together)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='signupemailpromo',
            name='first_year_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First year promotional price (price and discount should not be specified together)', max_digits=5, null=True),
        ),
    ]
