# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0169_auto_20190527_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplankey',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
