# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0170_subscriptionplankey_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orggroup',
            name='include_in_reports',
            field=models.BooleanField(default=True, help_text='Set to False if this group should be excluded from stats and reports'),
        ),
        migrations.AddField(
            model_name='orgmember',
            name='numArticlesRead30',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of articles read over the past 30 days. This is computed by a managment command.'),
        ),
    ]
