# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0171_auto_20190619_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='cmeRedeemed30',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sum of Orbit-CME credits redeemed over the past 30 days. This is computed by a managment command.', max_digits=6),
        ),
    ]
