# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0172_orgmember_cmeredeemed30'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='report name', max_length=60, unique=True)),
                ('description', models.CharField(blank=True, help_text='description', max_length=255)),
                ('resource', models.CharField(blank=True, help_text='resource name - must match an endpoint name in urls.py. The actual url will be reversed from the name', max_length=255)),
                ('last_generated', models.DateTimeField(blank=True, help_text='Date of report last generation', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enterprise Report',
            },
        ),
        migrations.AddField(
            model_name='orgfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('State License', 'State License'), ('DEA', 'DEA')], help_text='file type', max_length=30),
        ),
    ]
