# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0173_auto_20190702_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('New Provider', 'New Provider'), ('State License', 'State License'), ('DEA', 'DEA')], help_text='file type', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.PracticeSpecialty'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subspecialties',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.SubSpecialty'),
        ),
    ]
