# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0174_auto_20190704_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgfile',
            name='validated',
            field=models.BooleanField(default=False, help_text='Set to true after file has been validated. This must be done before using the file to update the db'),
        ),
        migrations.AlterField(
            model_name='orgfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('New Provider', 'New Provider'), ('State License', 'State License'), ('DEA', 'DEA'), ('Invalid', 'Invalid')], default='', help_text='file type', max_length=30),
        ),
        migrations.AlterField(
            model_name='orgfile',
            name='processed',
            field=models.BooleanField(default=False, help_text='Set to true after the file has been processed and db is updated'),
        ),
    ]
