# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0175_auto_20190705_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='statelicense',
            name='subcatg',
            field=models.IntegerField(blank=True, choices=[(0, 'Default'), (1, 'Telemedicine')], default=0, help_text='Sub-category for State licenses.'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='message',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterUniqueTogether(
            name='statelicense',
            unique_together=set([('user', 'state', 'licenseType', 'subcatg', 'expireDate', 'is_active')]),
        ),
    ]
