# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0176_auto_20190809_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_trial_credits',
            field=models.DecimalField(decimal_places=1, default=0, help_text=' Custom value for maximum credits allowed in Trial period. Overrides default value in settings.py', max_digits=3),
        ),
    ]
