# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0177_subscriptionplan_max_trial_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmeTagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name.', max_length=80, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CME Tag Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cmetag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='users.CmeTagCategory'),
        ),
    ]
