# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0178_auto_20190925_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='Password-ticket URL. This is a timed URL - set by ttl_days on the ticket.', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_trial_credits',
            field=models.DecimalField(decimal_places=1, default=0, help_text=' Custom value for maximum OrbitCME credits allowed in Trial period. -1 means: no redeeming allowed in Trial. 0 means: use default max_trial_credits in settings.py. A positive value: overrides default value in settings.py', max_digits=3),
        ),
    ]
