# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0180_auto_20191007_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTagFreq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numOffers', models.PositiveIntegerField(default=5, help_text='Specify a number gte to 5 in order to make this an article recommendation')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'URL Tag Frequencies',
                'db_table': 'trackers_urltagfreq',
                'managed': False,
            },
        ),
    ]
