# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0181_urltagfreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='welcome_offer_url',
            field=models.URLField(blank=True, help_text='URL for initial welcome offer. Must be an existing AllowedUrl already. If blank, then the default vaping article is used as the welcome offer.', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, help_text='discounted price in USD. Obsolete [no longer used].', max_digits=6),
        ),
    ]
