# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0182_auto_20191030_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ABANumber',
            field=models.CharField(blank=True, help_text='ABA ID', max_length=10),
        ),
        migrations.AlterField(
            model_name='cmeboost',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per credit in USD', max_digits=6),
        ),
    ]
