# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0183_auto_20191120_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='submitABADate',
            field=models.DateTimeField(blank=True, help_text='Set when entry is submitted to ABA organization for CME credit', null=True),
        ),
    ]
