# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-11 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0184_entry_submitabadate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='displayMonthlyPrice',
            field=models.BooleanField(default=False, help_text='Flag controls if UI displays price as per month in credit card screen'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='active',
            field=models.BooleanField(default=True, help_text='If false, this plan will no longer be available for new signups'),
        ),
    ]
