# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0185_auto_20191211_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_recs', models.PositiveIntegerField(default=0, help_text='Number of article recommendations for this tag to users on this plan')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cmeTags',
            field=models.ManyToManyField(blank=True, help_text='cmeTags to be added to profile for users on this plan', related_name='old_plans', to='users.CmeTag'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='welcome_offer_url',
            field=models.URLField(blank=True, help_text='URL for initial welcome offer. Must be an existing AllowedUrl already. If blank, then the default hard-coded article is used as the welcome offer.', max_length=500),
        ),
        migrations.AddField(
            model_name='plantag',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='plantag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmeTag'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='cmeTags to be added to profile for users on this plan', related_name='plans', through='users.Plantag', to='users.CmeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='plantag',
            unique_together=set([('plan', 'tag')]),
        ),
    ]
