# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0186_auto_20191217_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmetag',
            name='abbrev',
            field=models.CharField(blank=True, default='', help_text='Abbreviation used in ABA EventId', max_length=4),
        ),
    ]
