# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0187_cmetag_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowProfileStateTags',
            field=models.BooleanField(default=False, help_text='For individual plans: check box if this plan allows users to have State-specific CME tags'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Associate plan with a particular Organization - used for Enterprise plans, and Braintree Advanced plans.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='welcome_offer_url',
            field=models.URLField(blank=True, help_text='(Not implemented in frontend). URL for initial welcome offer. Must be an existing AllowedUrl already. If blank, then the default hard-coded article is used as the welcome offer.', max_length=500),
        ),
    ]
