# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0188_auto_20200204_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPlanset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['organization', 'plan'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(blank=True, default='', help_text='A new individual user is made a member of this org if their email_domain matches this value. e.g. radpartners.com', max_length=40),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If false, this plan is not available to the general public (e.g. RP Advanced).'),
        ),
        migrations.AddField(
            model_name='orgplanset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
        ),
        migrations.AddField(
            model_name='orgplanset',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan'),
        ),
        migrations.AlterUniqueTogether(
            name='orgplanset',
            unique_together=set([('organization', 'plan')]),
        ),
    ]
