# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0189_auto_20200205_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgmember',
            options={'verbose_name_plural': 'Organization Members'},
        ),
        migrations.AddField(
            model_name='orgmember',
            name='indiv_subscriber',
            field=models.BooleanField(default=False, help_text='Set to True when individual subscriber signs up with email that matches Org email domain.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='syncDataToOrg',
            field=models.BooleanField(default=False, help_text='Used for indiv_subscriber OrgMember users to allow them to opt-in to share data wit the Org.'),
        ),
    ]
