# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0191_auto_20200218_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmetag',
            name='exemptFrom1Tag',
            field=models.BooleanField(default=False, help_text='True if tag is exempt from the 1-tag-only policy on redeeming offers.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ABIMNumber',
            field=models.CharField(blank=True, help_text='ABIM ID (American Board of Internal Medicine)', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ABANumber',
            field=models.CharField(blank=True, help_text='ABA ID (American Board of Anesthesiology)', max_length=10),
        ),
    ]
