# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-15 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0192_auto_20200408_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='submitABIMDate',
            field=models.DateTimeField(blank=True, help_text='Set when entry is submitted to ABIM for MOC credit', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='submitABADate',
            field=models.DateTimeField(blank=True, help_text='Set when entry is submitted to ABA for CME credit', null=True),
        ),
    ]
