# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0193_auto_20200415_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='computeTeamStats',
            field=models.BooleanField(default=True, help_text='If True: provider stats will be computed daily. Set to False if org is not an active Enterprise org.'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='display_name',
            field=models.CharField(help_text='UPPERCASE. Used for search and display', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If false, this plan is not available to the general public (e.g. RP Advanced). Used for Braintree plans.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='welcome_offer_url',
            field=models.URLField(blank=True, help_text='URL for initial welcome offer. Must be an existing AllowedUrl in db. If blank, then the default hard-coded article is used as the welcome offer.', max_length=500),
        ),
    ]
