# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-22 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0194_auto_20200421_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercme',
            name='planEffect',
            field=models.IntegerField(choices=[(0, 'No change'), (1, 'Change'), (2, 'Unsure')], default=0),
        ),
    ]
