# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-28 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0195_auto_20200422_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='payout',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fixed payout. Is capped by the fully discounted price paid by convertee. Either bonus or payout must be specified.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Fractional multipler on fully discounted price paid by convertee. Either bonus or payout must be specified.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='displayLabel',
            field=models.CharField(blank=True, default='', help_text='Identifying label used by UI for display', max_length=60),
        ),
        migrations.AlterField(
            model_name='affiliatepayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='per-user payout paid to affiliate in USD.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='page_title_suffix',
            field=models.CharField(blank=True, default='', help_text='Common suffix for page titles will be stripped from the offer description.', max_length=60),
        ),
    ]
