# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0198_auto_20200623_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='#hastag_code. Must be unique.', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('specialties', models.ManyToManyField(blank=True, help_text='Assigned specialties', related_name='hashtags', to='users.PracticeSpecialty')),
                ('subspecialties', models.ManyToManyField(blank=True, help_text='Assigned sub-specialties', related_name='hashtags', to='users.SubSpecialty')),
            ],
        ),
        migrations.DeleteModel(
            name='InfluencerGroupManager',
        ),
        migrations.AlterModelOptions(
            name='influencermembership',
            options={'ordering': ['group', '-created'], 'verbose_name_plural': 'Influencer Group Membership'},
        ),
    ]
