# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0200_diffdiagnosis_garticlesearch_garticlesearchlog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowArticleSearch',
            field=models.BooleanField(default=False, help_text='Enable Related Article rail in plugin for this user.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowArticleSearch',
            field=models.BooleanField(default=False, help_text='Enable Related Article rail in plugin for users on this plan.'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='code',
            field=models.CharField(help_text="Unique Code (do not include the '#').", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='influencergroup',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text="Twitter handle (do not include the '@').", max_length=20),
        ),
    ]
