# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-10 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0202_auto_20200708_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxyname', models.CharField(help_text='proxy part of netloc only. Example: offcampus.lib.washington.edu', max_length=100, unique=True)),
                ('delimiter', models.CharField(help_text='delimiter used in the domain name. Example: -', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_proxypattern',
                'ordering': ['proxyname'],
                'managed': False,
            },
        ),
    ]
