# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0204_auto_20200716_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topicID', models.PositiveIntegerField(help_text='User-assigned numerical ID for this topic. Must be unique.', unique=True)),
                ('name', models.CharField(help_text='Topic short name. The tuple (specialty, name) must be unique.', max_length=60)),
                ('long_name', models.CharField(help_text='Topic long name', max_length=80)),
                ('alternate_name', models.CharField(blank=True, default='', help_text='Alternate name (e.g. from radiopaedia). Used to map from a different source.', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_studytopic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyTopicGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupID', models.PositiveIntegerField(help_text='User-assigned numerical ID for this group. Must be unique.', unique=True)),
                ('name', models.CharField(help_text='Group name. Must be unique', max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Optional description', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trackers_studytopicgroup',
                'managed': False,
            },
        ),
    ]
