# Generated by Django 2.2.15 on 2020-08-17 05:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0205_studytopic_studytopicgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authimpersonation',
            name='impersonator',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), models.Q(_negated=True, username__in=('admin', 'radmin'))), on_delete=django.db.models.deletion.CASCADE, related_name='impersonators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='is_unlisted',
            field=models.BooleanField(blank=True, default=False, help_text='True if site should be unlisted'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hasResidencyProgram',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='providerStat',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='dict'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='dict', help_text='A snapshot of the goals status for this user. It is computed by a management command run periodically.'),
        ),
    ]
