# Generated by Django 2.2.15 on 2020-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0206_auto_20200817_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicespecialty',
            name='gsearchengid',
        ),
        migrations.AddField(
            model_name='practicespecialty',
            name='internalSearchEngineid',
            field=models.CharField(blank=True, default='', help_text='Internal Google search engine ID to use for categorizing articles in this specialty. Used for ddx/studytopic assignment. Must match a valid ID defined in the google console.', max_length=50),
        ),
        migrations.AddField(
            model_name='practicespecialty',
            name='userSearchEngineid',
            field=models.CharField(blank=True, default='', help_text='Public Google search engine ID to use for the RelatedArticleRail for users in this specialty. Must match a valid ID defined in the google console.', max_length=50),
        ),
    ]
