# Generated by Django 2.2.15 on 2020-08-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0207_auto_20200819_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='cmeTags',
        ),
        migrations.AddField(
            model_name='plantag',
            name='num_diplay_in_panel',
            field=models.PositiveIntegerField(default=0, help_text='Max number of recommended articles to display in Plugin overflow panel for this tag. Must be less or than or equal to num_recs'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowDdx',
            field=models.BooleanField(default=False, help_text="Enable Ddx collection in plugin for users on this plan. This field is OR'd with the per-user assignment to the Ddx group to decide the permission."),
        ),
        migrations.AlterField(
            model_name='plantag',
            name='num_recs',
            field=models.PositiveIntegerField(default=0, help_text='Number of recommended articles for this tag created for users on this plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='allowArticleSearch',
            field=models.BooleanField(default=False, help_text="Enable Google Custom Search in plugin for users on this plan. This field is OR'd with the per-user assignment to the ArticleSearch group to decide the permission."),
        ),
    ]
