# Generated by Django 2.2.15 on 2020-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0208_auto_20200825_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantag',
            old_name='num_diplay_in_panel',
            new_name='num_display_panel',
        ),
    ]
