# Generated by Django 2.2.15 on 2020-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0209_auto_20200825_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GArticleSearchLog',
        ),
        migrations.AlterModelOptions(
            name='garticlesearch',
            options={'managed': False, 'verbose_name': 'Related Article Search', 'verbose_name_plural': 'Related Article Searches'},
        ),
        migrations.AlterField(
            model_name='plantag',
            name='num_display_panel',
            field=models.PositiveIntegerField(default=0, help_text='Max number of recommended articles to display in Plugin overflow panel. Must be less or than or equal to num_recs'),
        ),
    ]
