# Generated by Django 2.2.15 on 2020-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0210_auto_20200827_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adblocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('ios', models.BooleanField(default=False, help_text='Check box if this entry is for the ios app')),
                ('file_url', models.URLField(blank=True, default='', help_text='For ios app entry: S3 URL of the adblock file. Upload to the adblocker folder in the orbitcme-dev and orbitcme-prod S3 bucket. Filename should be unique.', max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'managed': False,
                'db_table': 'trackers_adblocker',
            },
        ),
    ]
