# Generated by Django 2.2.15 on 2020-09-02 22:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0211_adblocker'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblesite',
            name='journal_home_page',
            field=models.CharField(blank=True, default='', help_text='Journal homepage if different from domain_name. e.g. jamanetwork.com/journals/jamacardiology/ This allows the plugin to recognize the home page even though it itself is not a whitelisted article.', max_length=200),
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='site_type',
            field=models.PositiveIntegerField(choices=[(1, 'Journal'), (2, 'Wiki'), (3, 'Database')], default=1, help_text='Example: radiopaedia.org is a wiki. JAMA is a journal'),
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='domain_name',
            field=models.CharField(help_text='A proper domain name without the scheme and no slashes. Example: jamanetwork.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='domain_title',
            field=models.CharField(help_text='e.g. Journal of Nuclear Medicine', max_length=300),
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='verify_journal',
            field=models.BooleanField(default=False, help_text='If True, need to verify article belongs to an allowed journal before making offer. Used for ScienceDirect and similar sites.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='providerStat',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A snapshot of the goals status for this user. It is computed by a management command run periodically.'),
        ),
    ]
