# Generated by Django 2.2.15 on 2020-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0212_auto_20200902_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblesite',
            name='citation_journal_title',
            field=models.CharField(blank=True, default='', help_text='If this is a journal site, specify its citation_journal_title so that search results can be matched to this EligibleSite', max_length=200),
        ),
        migrations.AddField(
            model_name='eligiblesite',
            name='preferred_title_key',
            field=models.CharField(blank=True, default='', help_text='The title key name to use when extracting title from google search results. If not specified, will use citation_title.', max_length=40),
        ),
    ]
