# Generated by Django 2.2.15 on 2020-10-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0213_auto_20200903_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Orbit Procedure name. Must be unique.', max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidencyProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Training program type. Must be unique.', max_length=200, unique=True)),
                ('duration_years', models.IntegerField(default=0, help_text='Program duration in years.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eligiblesite',
            name='preferred_title_key',
            field=models.CharField(blank=True, default='', help_text='The title key name to use when extracting title from google search results. If not specified, will use title.', max_length=40),
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('program_type', models.ForeignKey(help_text='Training program type.', on_delete=django.db.models.deletion.PROTECT, to='users.ResidencyProgramType')),
                ('residency', models.ForeignKey(help_text='Residency/facility reference.', on_delete=django.db.models.deletion.PROTECT, to='users.ResidencyProgram')),
            ],
        ),
        migrations.CreateModel(
            name='OrbitProcedureMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facility name.', max_length=200, unique=True)),
                ('regex', models.CharField(help_text='Procedure name regex for this specific facility.', max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(help_text='Procedure reference for this match.', on_delete=django.db.models.deletion.CASCADE, to='users.OrbitProcedure')),
            ],
        ),
        migrations.CreateModel(
            name='OrbitCaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.IntegerField(choices=[(0, 'Diagnostic'), (1, 'Intervention')], default=1, help_text='Procedure type')),
                ('goal_value', models.IntegerField(default=0, help_text='Goal value.')),
                ('procedure', models.ForeignKey(help_text='Procedure reference for this goal.', on_delete=django.db.models.deletion.CASCADE, to='users.OrbitProcedure')),
                ('program_type', models.ForeignKey(help_text='Training program for this goal.', on_delete=django.db.models.deletion.CASCADE, to='users.ResidencyProgramType')),
                ('subspecialty', models.ForeignKey(help_text='Subspecialty.', on_delete=django.db.models.deletion.CASCADE, to='users.SubSpecialty')),
            ],
            options={
                'unique_together': {('program_type', 'procedure_type', 'subspecialty', 'procedure')},
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(help_text='NPI number of the resident.', max_length=20, unique=True)),
                ('cpt_code', models.CharField(help_text='CPT code of the procedure.', max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(help_text='Date and time of the actual procedure.')),
                ('age_category', models.CharField(help_text='Patient category: child or adult.', max_length=60)),
                ('facility', models.CharField(help_text='Facility.', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(help_text='Procedure reference for this case.', on_delete=django.db.models.deletion.PROTECT, to='users.OrbitProcedure')),
                ('profile', models.ForeignKey(blank=True, help_text='Internal resident profile ID.', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='users.Profile')),
            ],
            options={
                'unique_together': {('npi', 'procedure', 'timestamp')},
            },
        ),
    ]
