# Generated by Django 2.2.15 on 2020-09-15 06:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0214_auto_20200915_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tab title', max_length=30, unique=True)),
                ('icon1x', models.URLField(help_text='Tab icon URL', max_length=500)),
                ('icon2x', models.URLField(help_text='Tab icon URL 2x size', max_length=500)),
                ('icon3x', models.URLField(help_text='Tab icon URL 3x size', max_length=500)),
                ('contents', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON object containing the contents of the tab. See existing tabs as a guide.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='allowArticleHistory',
            field=models.BooleanField(default=True, help_text="Enable Article History rail in plugin for users on this plan. This field is OR'd with the per-user assignment to the ArticleHistory group to decide the permission."),
        ),
        migrations.CreateModel(
            name='PlanUITab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, help_text='Tab index')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UITab')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('plan', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='PlanUIMoreTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, help_text='Tab index')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionPlan')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UITab')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('plan', 'tab')},
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ui_more_tabs',
            field=models.ManyToManyField(blank=True, help_text='UI More Tab configuration', related_name='plan_more_tabs', through='users.PlanUIMoreTab', to='users.UITab'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ui_tabs',
            field=models.ManyToManyField(blank=True, help_text='UI Tab configuration', related_name='plan_tabs', through='users.PlanUITab', to='users.UITab'),
        ),
    ]
