# Generated by Django 2.2.15 on 2020-11-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0214_auto_20201028_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orbitprocedurematch',
            old_name='name',
            new_name='facility',
        ),
    ]
