# Generated by Django 2.2.15 on 2020-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0215_auto_20201102_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitprocedurematch',
            name='facility',
            field=models.CharField(help_text='Facility name (i.e. UCSD).', max_length=200),
        ),
        migrations.AlterField(
            model_name='orbitprocedurematch',
            name='regex',
            field=models.CharField(help_text='Procedure name regex for this specific facility.', max_length=500),
        ),
    ]
