# Generated by Django 2.2.15 on 2020-09-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0216_auto_20200916_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uitab',
            name='icon1x',
        ),
        migrations.RemoveField(
            model_name='uitab',
            name='icon2x',
        ),
        migrations.RemoveField(
            model_name='uitab',
            name='icon3x',
        ),
    ]
