# Generated by Django 2.2.15 on 2020-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0216_auto_20201102_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='procedure_name',
            field=models.CharField(default='', help_text='Procedure name as provided by facility.', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='cpt_code',
            field=models.CharField(help_text='CPT code of the procedure.', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='facility',
            field=models.CharField(help_text='Facility.', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='npi',
            field=models.CharField(help_text='NPI number of the resident.', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='procedure',
            field=models.ForeignKey(help_text='Procedure reference for this case.', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.OrbitProcedure'),
        ),
    ]
