# Generated by Django 2.2.15 on 2020-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0217_auto_20200916_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='createWelcomeOffer',
            field=models.BooleanField(default=True, help_text='Controls if the users on this plan get a welcome offer created for them at signup.'),
        ),
    ]
