# Generated by Django 2.2.15 on 2020-11-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0217_auto_20201103_1329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('npi', 'cpt_code', 'timestamp')},
        ),
    ]
