# Generated by Django 2.2.15 on 2020-11-05 05:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0218_auto_20201103_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
