# Generated by Django 2.2.15 on 2020-10-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0218_subscriptionplan_createwelcomeoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOnboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of onboarding type. Must be unique. Must be in-sync with what UI expects', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='onboarding_type',
            field=models.ForeignKey(blank=True, help_text='Onboarding type for this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='users.PlanOnboardType'),
        ),
    ]
