# Generated by Django 2.2.15 on 2020-11-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0219_auto_20201105_0526'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
            ],
        ),
    ]
