# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 06:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmegoal',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='wellnessgoal',
            name='interval',
        ),
        migrations.AddField(
            model_name='basegoal',
            name='interval',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Interval in years for recurring goal', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
