# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 04:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20180809_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(help_text='Page title', max_length=300)),
                ('domainTitle', models.CharField(help_text='Domain title e.g. Orbit Blog', max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('pubDate', models.DateField(blank=True, help_text='Publish Date', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.BaseGoal')),
            ],
        ),
        migrations.AlterField(
            model_name='cmegoal',
            name='dueDay',
            field=models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cmegoal',
            name='dueMonth',
            field=models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='cmegoal',
            name='licenseGoal',
            field=models.ForeignKey(blank=True, help_text='Must be selected if dueDate uses license expiration date. Null otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmegoals', to='goals.LicenseGoal'),
        ),
        migrations.AlterUniqueTogether(
            name='goalrecommendation',
            unique_together=set([('goal', 'url')]),
        ),
    ]
