# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20180809_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalrecommendation',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='goals.BaseGoal'),
        ),
    ]
