# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 23:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20180809_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='creditsEarned',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used for CMEGoals', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
