# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_recallowedurl'),
        ('goals', '0007_usergoal_creditsearned'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='sort order for goals list'),
        ),
        migrations.AddField(
            model_name='licensegoal',
            name='cmeTag',
            field=models.ForeignKey(blank=True, help_text='If specified, goal applies only to profile whose active tags contain this tag', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licensegoals', to='users.CmeTag'),
        ),
        migrations.AddField(
            model_name='licensegoal',
            name='daysBeforeDue',
            field=models.PositiveIntegerField(default=90, help_text='Days before license dueDate at which status switches from Complete to In-Progress'),
        ),
        migrations.AlterField(
            model_name='basegoal',
            name='dueDateType',
            field=models.IntegerField(choices=[(0, 'One-off. Due immediately'), (1, 'Recurring. Due on fixed MM/DD'), (2, 'Recurring. Due at any time counting back over interval'), (3, 'Recurring. Due on user birth date'), (4, 'Recurring. Due on license expiration date')]),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='completeDate',
            field=models.DateTimeField(blank=True, help_text='Used for Wellness goal completion date.', null=True),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Past Due'), (1, 'In Progress'), (2, 'Completed')], db_index=True),
        ),
    ]
