# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20180814_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergoal',
            options={'permissions': (('view_goal', 'Can view Goal'),)},
        ),
    ]
