# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20180816_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='compliance',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Past Due'), (1, 'In Progress'), (2, 'Completed')], db_index=True),
        ),
    ]
