# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_auto_20180830_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessgoal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='wellnessgoal',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='completeDate',
            field=models.DateTimeField(blank=True, help_text='Used for Training/Wellness goal completion date.', null=True),
        ),
        migrations.DeleteModel(
            name='WellnessGoal',
        ),
    ]
