# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 06:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_auto_20180927_0536'),
        ('goals', '0011_auto_20180926_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGoal',
            fields=[
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='traingoal', serialize=False, to='goals.BaseGoal')),
                ('title', models.CharField(help_text='Name of the course or training to be done', max_length=120)),
                ('dueMonth', models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('dueDay', models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.RemoveField(
            model_name='licensegoal',
            name='cmeTag',
        ),
        migrations.AddField(
            model_name='traininggoal',
            name='licenseGoal',
            field=models.ForeignKey(blank=True, help_text='Must be selected if dueDate uses license expiration date. Null otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traingoals', to='goals.LicenseGoal'),
        ),
        migrations.AddField(
            model_name='traininggoal',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traingoals', to='users.State'),
        ),
    ]
