# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20180927_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='valid',
            field=models.BooleanField(default=True, help_text='Used for TrainingGoal. Set/clear flag instead of deleting to preserve information'),
        ),
    ]
