# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_usergoal_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBaseGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Training-Goals',
                'indexes': [],
            },
            bases=('goals.basegoal',),
        ),
        migrations.AddField(
            model_name='traininggoal',
            name='daysBeforeDue',
            field=models.PositiveIntegerField(default=180, help_text='days before nextDueDate at which the next usergoal in a recurring series is created'),
        ),
    ]
