# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 06:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0154_auto_20190116_0648'),
        ('goals', '0015_auto_20190115_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRCmeGoal',
            fields=[
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='srcmegoal', serialize=False, to='goals.BaseGoal')),
                ('credits', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dueMonth', models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('dueDay', models.SmallIntegerField(blank=True, help_text='Must be specified if dueDateType is Fixed MMDD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('cmeTag', models.ForeignKey(help_text='State-specific CME Tag', on_delete=django.db.models.deletion.PROTECT, related_name='srcmegoals', to='users.CmeTag')),
                ('creditTypes', models.ManyToManyField(blank=True, help_text='Eligible creditTypes that satisfy this goal.', related_name='srcmegoals', to='users.CreditType')),
                ('licenseGoal', models.ForeignKey(blank=True, help_text='Must be selected if dueDate uses license expiration date. Null otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srcmegoals', to='goals.LicenseGoal')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srcmegoals', to='users.State')),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingBaseGoal',
        ),
        migrations.CreateModel(
            name='SRCmeBaseGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'SRCME-Goals',
                'indexes': [],
            },
            bases=('goals.basegoal',),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Used to filter goals by state', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usergoals', to='users.State'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='completeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='valid',
            field=models.BooleanField(default=True, help_text='Set/clear flag instead of deleting to preserve information'),
        ),
    ]
