# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0016_auto_20190117_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='is_composite_goal',
            field=models.BooleanField(default=False, help_text='True if goal represents a composite of multiple goals'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='srcmeGoals',
            field=models.ManyToManyField(related_name='usersrcmegoals', to='goals.SRCmeGoal'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Past Due'), (1, 'In Progress'), (2, 'Completed'), (3, 'Expired')], db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together=set([('user', 'goal', 'dueDate', 'is_composite_goal')]),
        ),
    ]
