# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 04:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0156_state_dotags'),
        ('goals', '0017_auto_20190122_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='creditsDueMonthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used for CMEGoals', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='srcmegoal',
            name='cmeTag',
            field=models.ForeignKey(blank=True, help_text='State-specific SR-CME Tag. Null means Any Topic', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='srcmegoals', to='users.CmeTag'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='cmeTag',
            field=models.ForeignKey(blank=True, help_text='Used with CmeGoal/SRCmeGoal. Null means Any Topic.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usergoals', to='users.CmeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together=set([('user', 'goal', 'dueDate', 'is_composite_goal', 'cmeTag')]),
        ),
    ]
