# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_auto_20190129_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='cmeGoals',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='srcmeGoals',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='constituentGoals',
            field=models.ManyToManyField(blank=True, help_text='Populated for composite goals', related_name='_usergoal_constituentGoals_+', to='goals.UserGoal'),
        ),
    ]
