# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0156_state_dotags'),
        ('goals', '0019_auto_20190129_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='creditTypes',
            field=models.ManyToManyField(blank=True, help_text='Eligible creditTypes that satisfy this goal (not used for composite goals).', related_name='usergoals', to='users.CreditType'),
        ),
    ]
