# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_usergoal_credittypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcmegoal',
            name='has_credit',
            field=models.BooleanField(default=True, help_text='Set to False if this is a zero-credit goal requirement (but set credits field value to 1)'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='creditTypes',
            field=models.ManyToManyField(blank=True, help_text='Eligible creditTypes that satisfy this goal (used for credit goals).', related_name='usergoals', to='users.CreditType'),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
