# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0021_auto_20190205_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Past Due'), (1, 'In Progress'), (2, 'Completed'), (3, 'Expired'), (4, 'New - uninitialized')], db_index=True),
        ),
    ]
