# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_auto_20190319_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='constituentGoals',
            field=models.ManyToManyField(blank=True, help_text='Populated for composite goals', related_name='compositeGoals', to='goals.UserGoal'),
        ),
    ]
