# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0023_auto_20190321_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmegoal',
            name='deaType',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'DEA in-state'), (2, 'DEA any-state')], default=0, help_text='For DEA licenses, choose either in-state or any-state'),
        ),
    ]
