# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0024_cmegoal_deatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcmegoal',
            name='deaType',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'DEA in-state'), (2, 'DEA any-state')], default=0, help_text='For DEA-specific goals, choose either in-state or any-state'),
        ),
        migrations.AlterField(
            model_name='cmegoal',
            name='deaType',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'DEA in-state'), (2, 'DEA any-state')], default=0, help_text='For DEA-specific goals, choose either in-state or any-state'),
        ),
    ]
