# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0025_auto_20190423_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='license',
            field=models.ForeignKey(blank=True, help_text='Used for goals that use license expireDate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergoals', to='users.StateLicense'),
        ),
    ]
